In [1]:
#Sesi4 Numpy for Data Analysis

import numpy as np
my_list=[1,2,3]
oneDim=np.array(my_list)
oneDim

array([1, 2, 3])

In [12]:
print(np.arange(4))
print(np.arange(0,10,2)) #start, stop, step

[0 1 2 3]
[0 2 4 6 8]


In [18]:
arr=np.array([1,2,3,4,5,6,7,8])
arr
np.append(arr, [1,2]) #append

array([1, 2, 3, 4, 5, 6, 8])

In [19]:
np.delete(arr,6) #delete elemen di index yang ditentukan

array([1, 2, 3, 4, 5, 6, 8])

In [21]:
np.sort(arr) #sorting

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
#Exercise in Session 4
#Soal1 1Dimensi
x=int(input('Start: ')) 
y=int(input('Stop: '))
np.arange(x,y,1) #start, stop, step

Start: 1
Stop: 28


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [67]:
#Soal1 2Dimensi
x=int(input('Start: ')) 
y=int(input('Stop: '))
m=int(input('2D Row: '))
n=int(input('2D Col: '))
np.arange(x,y,1).reshape(m,n)

Start: 1
Stop: 28
2D Row: 3
2D Col: 9


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [71]:
#Soal1 3Dimensi
x=int(input('Start: ')) 
y=int(input('Stop: '))
m=int(input('3Da1: '))
n=int(input('3Da2: '))
o=int(input('3Da3: '))
np.arange(x,y,1).reshape(m,n,o)

Start: 1
Stop: 28
3Da1: 9
3Da2: 3
3Da3: 0


ValueError: cannot reshape array of size 27 into shape (9,3,0)

In [74]:
#Soal2a and 2b
#n=int(input('No of integer: '))
a=int(input('Start: ')) #start
b=int(input('End: ')) #End
c=int(input('No of data: ')) #no of data
randomInt=np.random.randint(a,b,c)
print(randomInt)

#Soal2c
twoDrandomInt=randomInt.reshape(4,4)
print(twoDrandomInt)

#Soal2d
twoDrandomInt[::-1, :] 

Start: 1
End: 50
No of data: 16
[ 8 27 46 34 48 18 20 23 25 23  3 32 14 19 47 45]
[[ 8 27 46 34]
 [48 18 20 23]
 [25 23  3 32]
 [14 19 47 45]]


array([[14, 19, 47, 45],
       [25, 23,  3, 32],
       [48, 18, 20, 23],
       [ 8, 27, 46, 34]])

In [103]:
y=np.ones((10,10))*4
print(y)

[[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]]


In [104]:
y[1:9,1:9]=0 #or bisa juga y[1:-1, 1:-1]
print(y)

[[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]]
